{
 "title": "Auditd Dashboard",
 "description": "Dashboard for auditd logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "General Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sudo Usage",
     "type": "gauge",
     "description": "Shows total uses of sudo in the last 6 hours",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "  sum by (host) (\n    count_over_time(\n      {job=\"auditd\"} |= \"type=USER_CMD\" |= \"sudo\"\n      | logfmt\n      | label_format host=\"{{.host}}\"\n      [$__interval]\n    )\n  )"
      }
     ]
    },
    {
     "title": "Root Logins",
     "type": "gauge",
     "description": "All root logins in the last 6 hours",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "\n  sum by (host) (\n    count_over_time(\n      {job=\"auditd\"} |= \"USER_LOGIN\" |= \"acct=\\\"root\\\"\"\n      | logfmt\n      | label_format host=\"{{.host}}\"\n      [$__interval]\n    )\n  )\n\n"
      }
     ]
    },
    {
     "title": "Failed Logins",
     "type": "gauge",
     "description": "All failed logins in the last 6 hours",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "\n  sum by (host) (\n    count_over_time(\n      {job=\"auditd\"} |= \"USER_LOGIN\" |= \"res=failed\"\n      | logfmt\n      | label_format host=\"{{.host}}\"\n      [$__interval]\n    )\n  )\n"
      }
     ]
    },
    {
     "title": "Total Logins",
     "type": "gauge",
     "description": "Total Logins in the last 6 hours",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_over_time(\n  {job=\"auditd\"} |= \"type=USER_LOGIN\"\n  [$__interval]\n)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Privilege Escalation & Persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executed Binaries",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,\n  sum by (a0) (\n    count_over_time(\n      {job=\"auditd\"} |= \"type=EXECVE\"\n      | logfmt\n      [1h]\n    )\n  )\n)\n"
      }
     ]
    },
    {
     "title": "Sudo Usage",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "{job=\"auditd\"} |= \"type=USER_CMD\" |=\"sudo\"\n| logfmt\n| logfmt msg\n| keep addr, host, AUID, cmd"
      }
     ]
    },
    {
     "title": "Cronjobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "{job=\"auditd\"} |= \"EXECVE\" |= \"cron\"\n| logfmt\n| keep host, AUID, a0\n"
      }
     ]
    }
   ]
  },
  { "title": "Login Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Successful Logins",
   "type": "table",
   "description": "Shows who logged in from where to what machine using which account",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{job=\"auditd\"} |= \"type=USER_LOGIN\" |=\"res=success\"\n| logfmt\n| logfmt msg\n| keep addr, host, AUID"
    }
   ]
  },
  {
   "title": "Login Attempts",
   "type": "barchart",
   "description": "Shows login attempts to a machine",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "sum by (host) (\n  count_over_time({job=\"auditd\"} |= \"type=USER_LOGIN\" [$__interval])\n)"
    }
   ]
  },
  {
   "title": "Root Logins",
   "type": "bargauge",
   "description": "Shows all attempted root logins to which machines",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,\n  sum by (acct, host) (\n    count_over_time(\n      {job=\"auditd\"} |= \"USER_LOGIN\" |= \"acct=\\\"root\\\"\"\n      | logfmt\n      | label_format acct=\"{{.acct}}\", host=\"{{.host}}\"\n      [$__interval]\n    )\n  )\n)\n\n"
    }
   ]
  },
  {
   "title": "Multiple Failed Account Attempts from Same IP",
   "type": "bargauge",
   "description": "Shows the number of failed login attempts to each account and from what IP address",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,\n  sum by (acct, addr, host) (\n    count_over_time(\n      {job=\"auditd\"} |= \"USER_LOGIN\" |= \"res=failed\"\n      | logfmt\n      | label_format acct=\"{{.acct}}\", addr=\"{{.addr}}\", host=\"{{.host}}\"\n      [$__interval]\n    )\n  )\n)\n\n"
    }
   ]
  }
 ]
}