{
 "title": "Sysmon",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Timing Correlation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"syslog\"} |~ \"systemd\\\\[1\\\\]:\" |~ \"Finished\" [1m]))",
     "legendFormat": "Services"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"syslog\"} |~ \"<EventID>1</EventID>\" |~ `<Data Name=\"User\">root</Data>` [1m]))",
     "legendFormat": "Commands"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"syslog\"} |~ \"EventID>3</EventID\" | regexp `<Data Name=\"DestinationIp\">(?P<ip>[^<]+)</Data>` | ip != \"-\" [1m]))",
     "legendFormat": "Networks"
    }
   ]
  },
  { "title": "Network & Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Destination IPs",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "direction": "backward", "expr": "# happy cow" }
   ]
  },
  {
   "title": "Service Counts",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (service) (count_over_time({job=\"syslog\"} |~ \"systemd\\\\[1\\\\]:\" |~ \"Starting\"\n| regexp `Starting (?P<service>[^ ]+) -` [5m]))"
    }
   ]
  },
  {
   "title": "Binaries Accessed",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (image) (count_over_time({job=\"sysmon\"} |~ \"<Provider Name=\\\"Linux-Sysmon\\\"\" |~ \"<EventID>1</EventID>\"\n| regexp `<Data Name=\"Image\">(?P<image>[^<]+)</Data>` [5m]))"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"cgroup\"} |= ``"
    }
   ]
  },
  {
   "title": "CRON Jobs",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"syslog\"} |~ \"CRON\\\\[\" |~ \"CMD\"\n| regexp `CRON\\[(?P<pid>\\d+)\\]: \\((?P<user>[^)]+)\\) CMD \\((?P<command>.+)\\)$`"
    }
   ]
  },
  {
   "title": "System Processes",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "targets": [
    { "direction": "backward", "expr": "# happy cow" }
   ]
  },
  {
   "title": "Network Connections",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "targets": [
    { "direction": "backward", "expr": "# happy cow" }
   ]
  }
 ]
}